CeladonCity_Condominiums_Roof_Text_IKnowEverything::
    .string "I KNOW EVERYTHING!$"

CeladonCity_Condominiums_Roof_Text_RooftopEeveeRetreats::
    .string "EEVEE recoils and races back toward\n"
    .string "the floor below.$"

CeladonCity_Condominiums_Roof_Text_RooftopEeveeDartsAcrossRoof::
    .string "EEVEE holds its ground for a beat,\n"
    .string "then darts farther across the roof.$"

CeladonCity_Condominiums_Roof_Text_RooftopEeveeRetreatsOneStage::
    .string "EEVEE startles and retreats to its\n"
    .string "previous spot on the roof.$"

CeladonCity_Condominiums_Roof_Text_RooftopEeveeCalm::
    .string "EEVEE stops running. It watches you\n"
    .string "calmly now.$"

