PokemonLeague_LancesRoom_Text_Intro::
    .string "...Welcome, challenger.\p"
    .string "{RIVAL}: {PLAYER}!\p"
    .string "DUDE, YOU MADE IT!\p"
    .string "LET'S GOOOOOO!\p"
    .string "SURPRISE!\p"
    .string "I'M IN THE ELITE FOUR!$"

PokemonLeague_LancesRoom_Text_IntroWater::
    .string "Remember DITTO?\p"
    .string "Dude, look at this team now!\p"
    .string "DITTO and everybody are READY!\p"
    .string "No holding back.\p"
    .string "LET'S. GOOOOOO!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LancesRoom_Text_IntroElectric::
    .string "Remember PICHU?\p"
    .string "LOOK AT RAICHU NOW!\p"
    .string "Everybody's READY!\p"
    .string "No holding back.\p"
    .string "LET'S. GOOOOOO!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LancesRoom_Text_IntroFire::
    .string "You remember EEVEE back on ROUTE 22?\p"
    .string "Well... look at us now.\p"
    .string "FLAREON and the whole crew are READY!\p"
    .string "No holding back.\p"
    .string "LET'S. GOOOOOO!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LancesRoom_Text_RematchIntro::
    .string "{RIVAL}: {PLAYER}! I KNEW YOU'D BE BACK!\p"
    .string "Champion or not, you still have\n"
    .string "to get through me.\p"
    .string "And I've gotten stronger since\n"
    .string "last time.\p"
    .string "LET'S GOOOOOO!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LancesRoom_Text_Defeat::
    .string "YES!\p"
    .string "HAHAHA!\p"
    .string "THAT WAS AWESOME!\p"
    .string "That might've been our best battle\n"
    .string "ever.$"

PokemonLeague_LancesRoom_Text_RematchDefeat::
    .string "Ha! Still got it, huh?\p"
    .string "Fine. Go see who's waiting for you.$"

PokemonLeague_LancesRoom_Text_PostBattle::
    .string "There's still one TRAINER ahead.\p"
    .string "I'm not saying ANYTHING else.\p"
    .string "Go get 'em, {PLAYER}.$"

