#ifndef GUARD_CONSTANTS_APRICORN_H
#define GUARD_CONSTANTS_APRICORN_H

#define APRICORN_COLOR_COUNT 8
#define APRICORN_TREE_COUNT 12

#define APRICORN_TREE_REGROWTH_MINUTES 720
#define BALL_MASTER_BATCH_MINUTES 4320

enum ApricornColor
{
    APRICORN_COLOR_WHITE,
    APRICORN_COLOR_RED,
    APRICORN_COLOR_ORANGE,
    APRICORN_COLOR_YELLOW,
    APRICORN_COLOR_GREEN,
    APRICORN_COLOR_BLUE,
    APRICORN_COLOR_VIOLET,
    APRICORN_COLOR_BLACK,
};

enum ApricornTreeId
{
    APRICORN_TREE_NONE,
    APRICORN_TREE_ROUTE2_YELLOW,
    APRICORN_TREE_ROUTE3_BLACK,
    APRICORN_TREE_VIRIDIAN_FOREST_GREEN,
    APRICORN_TREE_ROUTE4_BLUE,
    APRICORN_TREE_ROUTE6_GREEN,
    APRICORN_TREE_ROUTE11_YELLOW,
    APRICORN_TREE_ROUTE10_BLACK,
    APRICORN_TREE_ROUTE8_ORANGE,
    APRICORN_TREE_ROUTE12_BLUE,
    APRICORN_TREE_ROUTE15_VIOLET,
    APRICORN_TREE_ROUTE21_NORTH_RED,
    APRICORN_TREE_ROUTE11_WHITE,
};

enum BallMasterState
{
    BALL_MASTER_STATE_AVAILABLE,
    BALL_MASTER_STATE_WORKING,
    BALL_MASTER_STATE_COMPLETE,
};

#define BALL_MASTER_FLAG_MET (1 << 0)

#define APRICORN_FLAG_WHITE_FIRST_HARVESTED (1 << 0)

enum ApricornTreeInteractionState
{
    APRICORN_TREE_INTERACT_EMPTY,
    APRICORN_TREE_INTERACT_READY,
    APRICORN_TREE_INTERACT_WHITE_BLOCKED,
    APRICORN_TREE_INTERACT_WHITE_RECOVERING,
    APRICORN_TREE_INTERACT_WHITE_FIRST_READY,
};

#endif // GUARD_CONSTANTS_APRICORN_H
