PokedexRating_Text_HowIsPokedexComingAlong::
	.string "OAK: Good to see you!\n"
	.string "How is your POKéDEX coming along?\p"
	.string "Here, let me take a look.$"

PokedexRating_Text_OakReward30::
	.string "OAK: Ah, {PLAYER}!\n"
	.string "Your POKéDEX is coming along splendidly!\p"
	.string "You've registered 30 different\n"
	.string "POKéMON as owned.\p"
	.string "Take this EXP. SHARE.\p"
	.string "It should help you with your research.$"

PokedexRating_Text_ReceivedExpShareFromOak::
	.string "{PLAYER} received the EXP. SHARE\n"
	.string "from PROF. OAK!$"

PokedexRating_Text_OakReward50::
	.string "OAK: Fifty POKéMON!\n"
	.string "Excellent work, {PLAYER}.\p"
	.string "You've learned a great deal about\n"
	.string "raising many different kinds of POKéMON.\p"
	.string "I think you've earned this.\p"
	.string "It contains PSYCHIC.$"

PokedexRating_Text_ReceivedTM54FromOak::
	.string "{PLAYER} received TM54\n"
	.string "from PROF. OAK!$"

PokedexRating_Text_OakReward75::
	.string "OAK: Seventy-five POKéMON!\n"
	.string "Your POKéDEX is becoming quite a record.\p"
	.string "I have a POKéMON here that deserves\n"
	.string "a good TRAINER.\p"
	.string "Take care of this CHANSEY, won't you?$"

PokedexRating_Text_ReceivedChanseyFromOak::
	.string "{PLAYER} received CHANSEY\n"
	.string "from PROF. OAK!$"

PokedexRating_Text_OakReward100::
	.string "OAK: One hundred POKéMON!\n"
	.string "Remarkable, {PLAYER}.\p"
	.string "Very few TRAINERS ever study such a\n"
	.string "wide variety of POKéMON so closely.\p"
	.string "You've earned this.\p"
	.string "It contains EARTHQUAKE.$"

PokedexRating_Text_ReceivedTM17FromOak::
	.string "{PLAYER} received TM17\n"
	.string "from PROF. OAK!$"

PokedexRating_Text_OakReward125::
	.string "OAK: One hundred twenty-five POKéMON!\n"
	.string "Outstanding!\p"
	.string "There is very little left for me to teach\n"
	.string "you about collecting POKéMON.\p"
	.string "I'd like you to raise this DRATINI.\p"
	.string "I think you'll do very well together.$"

PokedexRating_Text_ReceivedDratiniFromOak::
	.string "{PLAYER} received DRATINI\n"
	.string "from PROF. OAK!$"

PokedexRating_Text_OakGiftNoRoom::
	.string "OAK: It looks like you don't have room\n"
	.string "for another POKéMON right now.\p"
	.string "Make room in your party or PC and\n"
	.string "come see me again.$"

PokedexRating_Text_OakJoeyUnlockIntro::
	.string "OAK: {PLAYER}... 151 different species.\p"
	.string "Remarkable.\p"
	.string "Your research has reached a point very\n"
	.string "few Trainers ever achieve.\p"
	.string "But there is one final test I can offer you.\p"
	.string "Not of your POKéDEX.\p"
	.string "Of you.$"

PokedexRating_Text_OakCallJoey::
	.string "OAK: Joey! You can come in now.$"

PokedexRating_Text_OakIntroduceJoey::
	.string "OAK: This is Joey.\p"
	.string "He is the strongest Trainer in the world.$"

PokedexRating_Text_JoeyFirstChallenge::
	.string "JOEY: Hi! Professor Oak told me you were\n"
	.string "really strong.\p"
	.string "Wanna battle?$"

PokedexRating_Text_JoeyShortChallenge::
	.string "JOEY: Wanna battle?$"

PokedexRating_Text_JoeyDecline::
	.string "JOEY: Okay! I'll be here when you're ready.$"

PokedexRating_Text_JoeyPlayerWin::
	.string "JOEY: Whoa! You're really good!\p"
	.string "I haven't had a battle like that in a\n"
	.string "long time.$"

PokedexRating_Text_SeenXOwnedY::
	.string "The amount of progress you've made\n"
	.string "on your POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.\p"
	.string "{FONT_NORMAL}PROF. OAK's rating:$"

PokedexRating_Text_LessThan10::
	.string "You still have lots to do.\p"
	.string "Go into every patch of grass you\n"
	.string "see and look for POKéMON!$"

PokedexRating_Text_LessThan20::
	.string "It looks as if you're getting on\n"
	.string "the right track!\p"
	.string "Keep exploring new areas and recording\n"
	.string "the POKéMON you find.$"

PokedexRating_Text_LessThan30::
	.string "Your POKéDEX could use a bit more\n"
	.string "volume still!\p"
	.string "Try to catch other species of\n"
	.string "POKéMON!$"

PokedexRating_Text_LessThan40::
	.string "Good, it's apparent that you're\n"
	.string "trying hard!\p"
	.string "Keep looking in places you haven't\n"
	.string "searched carefully yet.$"

PokedexRating_Text_LessThan50::
	.string "Your POKéDEX is coming along quite\n"
	.string "well!\p"
	.string "I've given one of my AIDES an\n"
	.string "AMULET COIN. Be sure to get it!$"

PokedexRating_Text_LessThan60::
	.string "Ah, you've finally topped 50\n"
	.string "species!\p"
	.string "You're building a very respectable\n"
	.string "collection, {PLAYER}!$"

PokedexRating_Text_LessThan70::
	.string "Hoho! This is turning into quite the\n"
	.string "respectable POKéDEX!$"

PokedexRating_Text_LessThan80::
	.string "Very good!\p"
	.string "I think you'll collect even more\n"
	.string "POKéMON by going fishing!$"

PokedexRating_Text_LessThan90::
	.string "Wonderful! Let me guess… You\n"
	.string "like to collect things, don't you?$"

PokedexRating_Text_LessThan100::
	.string "I'm impressed!\n"
	.string "It must have been difficult to do!$"

PokedexRating_Text_LessThan110::
	.string "You've finally hit 100 species!\n"
	.string "I can't believe how good you are!$"

PokedexRating_Text_LessThan120::
	.string "You even have the evolved forms\n"
	.string "of POKéMON! Super!$"

PokedexRating_Text_LessThan130::
	.string "Excellent! Trade with friends to\n"
	.string "get some more!$"

PokedexRating_Text_LessThan140::
	.string "Outstanding!\n"
	.string "You've become a real pro at this!$"

PokedexRating_Text_LessThan150::
	.string "I have nothing left to say!\n"
	.string "You're the POKéMON PROFESSOR now!$"

PokedexRating_Text_Complete::
	.string "Your POKéDEX is entirely complete!\n"
	.string "Congratulations!!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "And your NATIONAL POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "I'll be looking forward to seeing\n"
	.string "you fill the NATIONAL POKéDEX!$"

PokedexRating_Text_YouveCompletedDex::
	.string "Finally…\p"
	.string "You've finally completed the\n"
	.string "POKéDEX!\p"
	.string "It's magnificent!\n"
	.string "Truly, this is a fantastic feat!$"

PokedexRating_Text_Wroooaaarrr::
	.string "Wroooooooaaaaaarrrr!$"

PokedexRating_Text_HaHa::
	.string "はあ はあ‥$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "Thank you, {PLAYER}!\n"
	.string "Sincerely, thank you!\l"
	.string "You've made my dream a reality!$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "OAK: Ah, welcome!\p"
	.string "Tell me, how is your POKéDEX\n"
	.string "coming along?\p"
	.string "Wahaha!\p"
	.string "Actually, I know how it is, but I\n"
	.string "love seeing it anyway!\p"
	.string "Let's see…$"