Thomas_Text_ViridianDollReceived::
	.string "THOMAS gave you THOMAS'S DOLL.$"

Thomas_Text_ViridianDollHandoff::
	.string "My sister's in SAFFRON. Give her\n"
	.string "that for me.\p"
	.string "Don't ask her to forgive me. Don't\n"
	.string "tell her I had a good reason.\p"
	.string "Just... tell her I'm sorry.\p"
	.string "And RED... beat GIOVANNI.$"

Thomas_Text_ViridianDollNoRoom::
	.string "I need you to take something to my\n"
	.string "sister in SAFFRON.\p"
	.string "Make room in your KEY ITEMS and\n"
	.string "come back.$"
