CeruleanCity_House2_Text_RocketsStoleProperty::
    .string "Those miserable ROCKETS!\p"
    .string "They tore through our house\n"
    .string "and took our training gear,\p"
    .string "valuables, and other things.$"

CeruleanCity_House2_Text_RocketTookProperty::
    .string "TEAM ROCKET took a whole bag\n"
    .string "of our things!$"

CeruleanCity_House2_Text_ReturnedStolenGoods::
    .string "That's our stuff!\p"
    .string "The training gear…\n"
    .string "everything!\p"
    .string "I thought it was gone for good.\p"
    .string "Please, take this.\p"
    .string "It was part of our training set.\n"
    .string "You've earned it more than we\p"
    .string "have.$"

CeruleanCity_House2_Text_ReceivedTM08::
    .string "{PLAYER} received TM08 from\n"
    .string "the homeowner.$"

CeruleanCity_House2_Text_PostClearThanks::
    .string "Thank you for bringing our\n"
    .string "things back.$"

CeruleanCity_House2_Text_LassThanks::
    .string "You got everything back!\n"
    .string "Thank you!$"

CeruleanCity_House2_Text_TeamRocketLeftWayOut::
    .string "TEAM ROCKET left a way out!$"

