Route22_Text_EarlyRivalIntro::
	.string "{RIVAL}: {PLAYER}! Dude! Perfect timing!\p"
	.string "I've been DYING to try this!\p"
	.string "Check out my EEVEE!\n"
	.string "This little guy is RADICAL!\p"
	.string "C'MON! LET'S BATTLE!$"

Route22_Text_EarlyRivalDefeat::
	.string "WHOA! That was AWESOME!\p"
	.string "EEVEE, you were incredible!\p"
	.string "{PLAYER}, we are DEFINITELY\n"
	.string "doing that again!$"

Route22_Text_EarlyRivalVictory::
	.string "LET'S GOOOOOO!\p"
	.string "Did you SEE EEVEE out there?!\p"
	.string "That was sick! We gotta battle\n"
	.string "again sometime!$"

Route22_Text_EarlyRivalPostBattle::
	.string "Man, that was FUN!\p"
	.string "I'm gonna keep training EEVEE.\n"
	.string "Next time'll be even better!$"

@ Translated in RB as "{RIVAL}: What? Why do I have 2 POKéMON? You should catch some more too!"
Route22_Text_RivalShouldCatchSomeMons::
	.string "{RIVAL}“なんだ？\n"
	.string "ポケモン　2ひきも\l"
	.string "もってるの　なぜか　だって？\p"
	.string "おまえも\n"
	.string "つかまえれば　いい　じゃん！$"

Route22_Text_LateRivalIntro::
	.string "{RIVAL}: What? {PLAYER}!\n"
	.string "What a surprise to see you here!\p"
	.string "So you're going to the POKéMON\n"
	.string "LEAGUE?\p"
	.string "You collected all the BADGES, too?\n"
	.string "That's cool!\p"
	.string "Then I'll whip you, {PLAYER}, as a\n"
	.string "warm-up for the POKéMON LEAGUE!\p"
	.string "Come on!$"

Route22_Text_LateRivalDefeat::
	.string "What!?\p"
	.string "I was just careless, you!$"

Route22_Text_LateRivalPostBattle::
	.string "That loosened me up.\n"
	.string "I'm ready for the POKéMON LEAGUE!\p"
	.string "{PLAYER}, you need more practice.\p"
	.string "But hey, you know that!\n"
	.string "I'm out of here. Smell ya!$"

@ Translated in RB as "{RIVAL}: Hahaha! {PLAYER}! That's your best? You're nowhere near as good as me, pal! Go train some more! You loser!"
Route22_Text_LateRivalVictory::
	.string "{RIVAL}“ひゃははッ　{PLAYER}ー！\n"
	.string "それで　がんばってるのかよ！\l"
	.string "おれの　さいのうに　くらべりゃ\l"
	.string "{PLAYER}は　まだまだ　だな！\p"
	.string "もっと　れんしゅう　こいよ！\n"
	.string "あははーッ！$"

Route22_Text_LeagueGateSign::
	.string "POKéMON LEAGUE\n"
	.string "Front Gate$"

