VermilionCity_House2_Text_DoYouHaveMonWantToTradeForMyMon::
	.string "Hi!\n"
	.string "Do you have a {STR_VAR_1}?\p"
	.string "Want to trade it for my\n"
	.string "{STR_VAR_2}?$"

VermilionCity_House2_Text_ThatsTooBad::
	.string "That's too bad.$"

VermilionCity_House2_Text_ThisIsNoMon::
	.string "…This is no {STR_VAR_1}.\p"
	.string "If you get one, please trade it\n"
	.string "to me!$"

VermilionCity_House2_Text_ThankYou::
	.string "Thank you!$"

VermilionCity_House2_Text_HowIsMyOldMon::
	.string "How is my old {STR_VAR_2}?\p"
	.string "My {STR_VAR_1} is doing great!$"


VermilionCity_House2_Text_ImugiPreTrade::
    .string "I've always liked stories about\n"
    .string "serpents that dream of becoming\l"
    .string "dragons.\p"
    .string "Your EKANS has that look about it…\p"
    .string "Tell you what. Trade it to me, and\n"
    .string "I'll give you a POKéMON that's\l"
    .string "already chasing that dream.$"

VermilionCity_House2_Text_ImugiPostTrade::
    .string "Take good care of IMUGI.\p"
    .string "Someday, that little dragon's going\n"
    .string "to grow wings.$"
