ViridianCity_Mart_Text_YouCameFromPallet::
    .string "Hey!\n"
    .string "You came from PALLET TOWN?$"

ViridianCity_Mart_Text_TakeThisToProfOak::
    .string "You know PROF. OAK, right?\p"
    .string "His order came in.\n"
    .string "Can I get you to take it to him?$"

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk::
    .string "{PLAYER} received OAK'S PARCEL\n"
    .string "from the POKéMON MART clerk.$"

ViridianCity_Mart_Text_SayHiToOakForMe::
    .string "Okay, thanks! Please say hi to\n"
    .string "PROF. OAK for me, too.$"

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes::
    .string "This shop does good business in\n"
    .string "ANTIDOTES, I've heard.$"

ViridianCity_Mart_Text_GotToBuySomePotions::
    .string "I've got to buy some POTIONS.\p"
    .string "You never know when your POKéMON\n"
    .string "will need quick healing.$"


ViridianCity_Mart_Text_ReturnRocketGoods:
	.string "Those are ours!\p"
	.string "They disappeared from a delivery\n"
	.string "this morning.\p"
	.string "You actually got them back?\n"
	.string "Thank you. Really.\p"
	.string "Take these.\p"
	.string "You'll make better use of them\n"
	.string "than I will.$"

ViridianCity_Mart_Text_LoosePaper:
	.string "A loose paper was inside the bag.\n"
	.string "It doesn't belong to the shop.$"

ViridianCity_Mart_Text_RocketThanks:
	.string "Thank you. Really.$"
